### PR TITLE
Add the MIT license

### PR DESCRIPTION
**Pull request by Garanas**
A license is healthy to have in general, but specifically we'd like to add a license to the repository so that the content can be re-used in other places. One example is the project of @4z0t . See also:

- https://github.com/4z0t/SCFA-python-patcher

As discussed on [Discord](https://discord.com/channels/197033481883222026/1270400016804220970).

In order to do this we need to acknowledgement of all existing contributors that they are fine with their work being licensed in the MIT license. This includes:

- [x] @KionX 
- [x] @4z0t 
- [x] @Hdt80bro 
- [x] @Sheikah45 
- [x] @Garanas 
- [x] @Strogoo 
- [x] @RutreD

Please acknowledge that you accept or decline the introduction of a license.

### CODE REVIEW

**Comment by Garanas** [comment]
@4z0t please add a message here that you're fine with licensing your work to MIT.

**Comment by 4z0t** [comment]
I'm fine with licensing mywork to MIT.

**Comment by KionX** [comment]
Ok.

**Comment by Sheikah45** [comment]
I approve

**Comment by Strogoo** [comment]
Approve

**Comment by Garanas** [comment]
Thank you everyone - I'll merge this in 👍

**Pull request merged**
