### PR TITLE
Add Lua UI CopyToClipboard

### PR DESCRIPTION
**Pull request by 4z0t**

### CODE REVIEW

**Comment by Garanas** [comment]
What if we call it `CopyToClipboard`, without the `UI_` prefix?

**Comment by Garanas** [comment]
And for my idea, is it dangerous to give programmatic access to the clipboard? Does it have side effects, or other consequences?

**Comment by 4z0t** [comment]
> And for my idea, is it dangerous to give programmatic access to the clipboard? Does it have side effects, or other consequences?

It only writes string in it. Can't really tell if it can cause issues.

**Comment by 4z0t** [comment]
We can allow it only for lobby, so, players can copy stuff that is written by others for translation idk

**Comment by Garanas** [comment]
@Sheikah45 do you know whether programmatic access to clipboard is dangerous?

**Comment by Sheikah45** [comment]
Technically read access to the clipboard could be used to exfiltrate user secrets but this would have to be coupled with some other operation to get it out of the memory of the program.

Write access could be used to manipulate people's clipboard so that they insert different information than they expect.

Those are the two main considerations with giving a program clipboard access.

**Comment by Garanas** [comment]
If I'm not mistaken then this would only involve write access. If there's no other security concerns, then I suppose we can start by allowing write access to the clipboard in the lobby. It would be nice to be able to copy the content of a message, for example

**Pull request merged**
