### PR TITLE
Adjust error messages

### PR DESCRIPTION
**Pull request by Hdt80bro**
It was something pretty simple that I figured would help me get into binary patching. Currently, the error message for bad argument types goes "attempt to use as string a function value" when it *receives* a function value and *expects* a string, which is not how that reads. So I'm trying to get it to go "expected string but got function" though I seem to be having trouble picking the right virtual addresses.

### CODE REVIEW

**Comment by KionX** [comment]
You have a file offset, but you need a virtual address. Add 0x400000 to all addresses.

**Comment by Hdt80bro** [comment]
Thanks, that did it! Which binary is supposed to be patched by the way? The original one I have from steam is definitely not the same one that's deployed with FAF and it's letting me know.

**Comment by KionX** [comment]
https://github.com/FAForever/FA-Binary-Patches/blob/master/.github/workflows/upload.yml#L37

**Comment by Hdt80bro** [comment]
Thank you for the help!

**Pull request merged**
