### PR TITLE
Fix escaped empty string in logging functions

### PR DESCRIPTION
**Pull request by Hdt80bro**

### CODE REVIEW

**Comment by KionX** [comment]
The address is incorrect. Maybe it's better to use TAB as LuaJIT? Macros were added only for __COUNTER__?

I tend to close this PR. And I'll add it myself.

**Comment by Hdt80bro** [comment]
I added macros to make the assembly more readable, but now that I've done it... looking at it isn't more readable... I'll revert that change and look at the address again.

The current way `LOG` or `SPEW` is trying to be used is for something like `LOG("File ", file, " not found")` so that they don't have to use string concatenation or `string.format`. I nearly used a space, but I decided against forcing the user to used any particular separator.

**Comment by Hdt80bro** [comment]
Should be good now

**Comment by KionX** [comment]
It doesn't seem to be working.
```
UI_Lua LOG("123", _G, "321")
INFO: 123\000table: 10299C58\000321

UI_Lua LOG("123 ", _G, "321")
INFO: 123 , _G,  321
```
E09AEC "\%03o" works.
```
UI_Lua LOG("123", _G, "321")
INFO: 123table: 10299C58321
```
And yet need a space or tab. Have you checked the patch?

**Comment by Hdt80bro** [comment]
Rats, there was only one "\000" string so I figured that was it and thus an overlooked empty string. It's more complicated than that though.

**Comment by Hdt80bro** [comment]
By the way, what environment are you using to compile? I've had to make several local changes to get it to not error.

**Comment by Hdt80bro** [comment]
>```
> UI_Lua LOG("123", _G, "321")
> INFO: 123table: 10299C58321
This doesn't work Lua side by the way

**Comment by Hdt80bro** [comment]
We might consider looking at how `_ALERT` works, since that seems to be functioning properly

**Comment by KionX** [comment]
_ALERT refers to the LOG that is used in init.

**Comment by Hdt80bro** [comment]
It still works after init, but SPEW, LOG, and WARN behave differerently:
```lua
_ALERT("b", "c") --> INFO: b	c
SPEW("b", "c")   --> DEBUG: b000c
LOG("b", "c")    --> INFO: b000c
WARN("b", "c")   --> WARNING: b000c
```

**Comment by KionX** [comment]
So what do you want from me?

**Comment by Hdt80bro** [comment]
Hold for now while I look into the best way to fix this; I've already converted this to a draft

**Comment by KionX** [comment]
Committed my version.
I'm closing it until there are no other offers.

**Pull request closed without merging**
