### PR TITLE
Improve TeamColorMode()

### PR DESCRIPTION
**Pull request by Strogoo**

### CODE REVIEW

**Comment by Garanas** [comment]
@KionX Can you review this pull request? It is linked to this pull request: https://github.com/FAForever/fa/pull/3650

**Comment by KionX** [comment]
To avoid problems with LuaJIT, you should not work with the Lua stack directly.

**Comment by Garanas** [comment]
@KionX Can you look at this again?

**Comment by KionX** [comment]
It works the same as before.

**Comment by Strogoo** [comment]
Well, since you stopped working on Luajit, I guess it can be merged without changes now? Anyway, I'll be busy next 3-4 weeks, so can't work on it

**Comment by KionX** [comment]
Since this patch is not backward compatible, I will merge before updating the exe.

**Comment by KionX** [comment]
This PR is no longer compatible with the new patcher.

**Pull request closed without merging**
